// generated by go run gen-fonts.go; DO NOT EDIT

// Package antonregular provides the "Anton Regular" TrueType font
// from the Anton font family.
package antonregular // import "github.com/go-fonts/anton/antonregular"

import _ "embed"

// TTF is the data for the "Anton Regular" TrueType font.
//
//go:embed Anton-Regular.ttf
var TTF []byte
